# Generated by Django 5.0.6 on 2024-06-12 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('preco', models.FloatField()),
                ('informacoes', models.TextField()),
                ('ativo', models.BooleanField()),
                ('quantidade', models.IntegerField()),
                ('img_url_principal', models.TextField(default='')),
                ('img_url_secundaria', models.TextField(default='')),
                ('img_url_lateral', models.TextField(default='')),
                ('img_url_superior', models.TextField(default='')),
            ],
        ),
    ]
