# Generated by Django 5.0.6 on 2024-06-13 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojinha', '0002_contato'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
