# Generated by Django 5.0.6 on 2024-06-13 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojinha', '0003_promocao'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocao',
            name='novo_preco',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='promocao',
            name='produto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lojinha.produto'),
        ),
    ]
