# Generated by Django 5.0.6 on 2024-06-13 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojinha', '0005_rename_endereco_contato_mensagem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='link_compra',
            field=models.URLField(null=True),
        ),
    ]
